/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-01-14 17:53:03 UTC)
 * on 2015-03-26 at 00:22:31 UTC 
 * Modify at your own risk.
 */

package com.example.app.datosendpoint;

/**
 * Service definition for Datosendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link DatosendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Datosendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the datosendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://grupo3isst.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "datosendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Datosendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Datosendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getDatos".
   *
   * This request holds the parameters needed by the datosendpoint server.  After setting any optional
   * parameters, call the {@link GetDatos#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetDatos getDatos(java.lang.Long id) throws java.io.IOException {
    GetDatos result = new GetDatos(id);
    initialize(result);
    return result;
  }

  public class GetDatos extends DatosendpointRequest<com.example.app.datosendpoint.model.Datos> {

    private static final String REST_PATH = "datos/{id}";

    /**
     * Create a request for the method "getDatos".
     *
     * This request holds the parameters needed by the the datosendpoint server.  After setting any
     * optional parameters, call the {@link GetDatos#execute()} method to invoke the remote operation.
     * <p> {@link
     * GetDatos#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetDatos(java.lang.Long id) {
      super(Datosendpoint.this, "GET", REST_PATH, null, com.example.app.datosendpoint.model.Datos.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetDatos setAlt(java.lang.String alt) {
      return (GetDatos) super.setAlt(alt);
    }

    @Override
    public GetDatos setFields(java.lang.String fields) {
      return (GetDatos) super.setFields(fields);
    }

    @Override
    public GetDatos setKey(java.lang.String key) {
      return (GetDatos) super.setKey(key);
    }

    @Override
    public GetDatos setOauthToken(java.lang.String oauthToken) {
      return (GetDatos) super.setOauthToken(oauthToken);
    }

    @Override
    public GetDatos setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetDatos) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetDatos setQuotaUser(java.lang.String quotaUser) {
      return (GetDatos) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetDatos setUserIp(java.lang.String userIp) {
      return (GetDatos) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetDatos setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetDatos set(String parameterName, Object value) {
      return (GetDatos) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertDatos".
   *
   * This request holds the parameters needed by the datosendpoint server.  After setting any optional
   * parameters, call the {@link InsertDatos#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.example.app.datosendpoint.model.Datos}
   * @return the request
   */
  public InsertDatos insertDatos(com.example.app.datosendpoint.model.Datos content) throws java.io.IOException {
    InsertDatos result = new InsertDatos(content);
    initialize(result);
    return result;
  }

  public class InsertDatos extends DatosendpointRequest<com.example.app.datosendpoint.model.Datos> {

    private static final String REST_PATH = "datos";

    /**
     * Create a request for the method "insertDatos".
     *
     * This request holds the parameters needed by the the datosendpoint server.  After setting any
     * optional parameters, call the {@link InsertDatos#execute()} method to invoke the remote
     * operation. <p> {@link
     * InsertDatos#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.example.app.datosendpoint.model.Datos}
     * @since 1.13
     */
    protected InsertDatos(com.example.app.datosendpoint.model.Datos content) {
      super(Datosendpoint.this, "POST", REST_PATH, content, com.example.app.datosendpoint.model.Datos.class);
    }

    @Override
    public InsertDatos setAlt(java.lang.String alt) {
      return (InsertDatos) super.setAlt(alt);
    }

    @Override
    public InsertDatos setFields(java.lang.String fields) {
      return (InsertDatos) super.setFields(fields);
    }

    @Override
    public InsertDatos setKey(java.lang.String key) {
      return (InsertDatos) super.setKey(key);
    }

    @Override
    public InsertDatos setOauthToken(java.lang.String oauthToken) {
      return (InsertDatos) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertDatos setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertDatos) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertDatos setQuotaUser(java.lang.String quotaUser) {
      return (InsertDatos) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertDatos setUserIp(java.lang.String userIp) {
      return (InsertDatos) super.setUserIp(userIp);
    }

    @Override
    public InsertDatos set(String parameterName, Object value) {
      return (InsertDatos) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listDatos".
   *
   * This request holds the parameters needed by the datosendpoint server.  After setting any optional
   * parameters, call the {@link ListDatos#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public ListDatos listDatos() throws java.io.IOException {
    ListDatos result = new ListDatos();
    initialize(result);
    return result;
  }

  public class ListDatos extends DatosendpointRequest<com.example.app.datosendpoint.model.CollectionResponseDatos> {

    private static final String REST_PATH = "datos";

    /**
     * Create a request for the method "listDatos".
     *
     * This request holds the parameters needed by the the datosendpoint server.  After setting any
     * optional parameters, call the {@link ListDatos#execute()} method to invoke the remote
     * operation. <p> {@link
     * ListDatos#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListDatos() {
      super(Datosendpoint.this, "GET", REST_PATH, null, com.example.app.datosendpoint.model.CollectionResponseDatos.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListDatos setAlt(java.lang.String alt) {
      return (ListDatos) super.setAlt(alt);
    }

    @Override
    public ListDatos setFields(java.lang.String fields) {
      return (ListDatos) super.setFields(fields);
    }

    @Override
    public ListDatos setKey(java.lang.String key) {
      return (ListDatos) super.setKey(key);
    }

    @Override
    public ListDatos setOauthToken(java.lang.String oauthToken) {
      return (ListDatos) super.setOauthToken(oauthToken);
    }

    @Override
    public ListDatos setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListDatos) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListDatos setQuotaUser(java.lang.String quotaUser) {
      return (ListDatos) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListDatos setUserIp(java.lang.String userIp) {
      return (ListDatos) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListDatos setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListDatos setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListDatos set(String parameterName, Object value) {
      return (ListDatos) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeDatos".
   *
   * This request holds the parameters needed by the datosendpoint server.  After setting any optional
   * parameters, call the {@link RemoveDatos#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public RemoveDatos removeDatos(java.lang.Long id) throws java.io.IOException {
    RemoveDatos result = new RemoveDatos(id);
    initialize(result);
    return result;
  }

  public class RemoveDatos extends DatosendpointRequest<Void> {

    private static final String REST_PATH = "datos/{id}";

    /**
     * Create a request for the method "removeDatos".
     *
     * This request holds the parameters needed by the the datosendpoint server.  After setting any
     * optional parameters, call the {@link RemoveDatos#execute()} method to invoke the remote
     * operation. <p> {@link
     * RemoveDatos#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveDatos(java.lang.Long id) {
      super(Datosendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveDatos setAlt(java.lang.String alt) {
      return (RemoveDatos) super.setAlt(alt);
    }

    @Override
    public RemoveDatos setFields(java.lang.String fields) {
      return (RemoveDatos) super.setFields(fields);
    }

    @Override
    public RemoveDatos setKey(java.lang.String key) {
      return (RemoveDatos) super.setKey(key);
    }

    @Override
    public RemoveDatos setOauthToken(java.lang.String oauthToken) {
      return (RemoveDatos) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveDatos setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveDatos) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveDatos setQuotaUser(java.lang.String quotaUser) {
      return (RemoveDatos) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveDatos setUserIp(java.lang.String userIp) {
      return (RemoveDatos) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveDatos setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveDatos set(String parameterName, Object value) {
      return (RemoveDatos) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateDatos".
   *
   * This request holds the parameters needed by the datosendpoint server.  After setting any optional
   * parameters, call the {@link UpdateDatos#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.example.app.datosendpoint.model.Datos}
   * @return the request
   */
  public UpdateDatos updateDatos(com.example.app.datosendpoint.model.Datos content) throws java.io.IOException {
    UpdateDatos result = new UpdateDatos(content);
    initialize(result);
    return result;
  }

  public class UpdateDatos extends DatosendpointRequest<com.example.app.datosendpoint.model.Datos> {

    private static final String REST_PATH = "datos";

    /**
     * Create a request for the method "updateDatos".
     *
     * This request holds the parameters needed by the the datosendpoint server.  After setting any
     * optional parameters, call the {@link UpdateDatos#execute()} method to invoke the remote
     * operation. <p> {@link
     * UpdateDatos#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.example.app.datosendpoint.model.Datos}
     * @since 1.13
     */
    protected UpdateDatos(com.example.app.datosendpoint.model.Datos content) {
      super(Datosendpoint.this, "PUT", REST_PATH, content, com.example.app.datosendpoint.model.Datos.class);
    }

    @Override
    public UpdateDatos setAlt(java.lang.String alt) {
      return (UpdateDatos) super.setAlt(alt);
    }

    @Override
    public UpdateDatos setFields(java.lang.String fields) {
      return (UpdateDatos) super.setFields(fields);
    }

    @Override
    public UpdateDatos setKey(java.lang.String key) {
      return (UpdateDatos) super.setKey(key);
    }

    @Override
    public UpdateDatos setOauthToken(java.lang.String oauthToken) {
      return (UpdateDatos) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateDatos setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateDatos) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateDatos setQuotaUser(java.lang.String quotaUser) {
      return (UpdateDatos) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateDatos setUserIp(java.lang.String userIp) {
      return (UpdateDatos) super.setUserIp(userIp);
    }

    @Override
    public UpdateDatos set(String parameterName, Object value) {
      return (UpdateDatos) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Datosendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Datosendpoint}. */
    @Override
    public Datosendpoint build() {
      return new Datosendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link DatosendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setDatosendpointRequestInitializer(
        DatosendpointRequestInitializer datosendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(datosendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
